import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAppContext } from '../context/AppContext';
import { InsightReport } from '../constants/mockData';
import { Colors, Radius, Shadow, Spacing, Typography } from '../constants/theme';

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  });
}

export default function InsightReportScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { saveInsight } = useAppContext();
  const { reportJson } = useLocalSearchParams<{ reportJson: string }>();

  let report: InsightReport | null = null;
  try {
    report = JSON.parse(reportJson ?? '{}') as InsightReport;
  } catch {
    report = null;
  }

  function handleSave() {
    if (!report) return;
    saveInsight(report);
    router.replace('/diary');
  }

  function handleDiscard() {
    Alert.alert('Discard Insight?', "This report won't be saved.", [
      { text: 'Keep reading', style: 'cancel' },
      { text: 'Discard', style: 'destructive', onPress: () => router.replace('/diary') },
    ]);
  }

  if (!report) {
    return (
      <View style={[styles.container, { paddingTop: insets.top, alignItems: 'center', justifyContent: 'center' }]}>
        <Text style={{ color: Colors.muted }}>Could not load report.</Text>
        <TouchableOpacity onPress={() => router.back()}>
          <Text style={{ color: Colors.sage, marginTop: 12, fontWeight: '600' }}>Go back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.headerEyebrow}>Generated {formatDate(report.generatedAt)}</Text>
          <Text style={styles.headerTitle}>Your Health Insight</Text>
        </View>
        <View style={styles.headerBadge}>
          <Text style={styles.headerBadgeText}>✦ AI Report</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Eating profile */}
        <View style={[styles.card, styles.cardHero]}>
          <View style={styles.cardHeaderRow}>
            <Text style={styles.cardEmoji}>🌱</Text>
            <Text style={styles.cardTitle}>Your Eating Profile</Text>
          </View>
          <Text style={styles.cardBody}>{report.eatingProfile}</Text>
        </View>

        {/* Alignment */}
        <View style={styles.card}>
          <View style={styles.cardHeaderRow}>
            <Text style={styles.cardEmoji}>🎯</Text>
            <Text style={styles.cardTitle}>Goal Alignment</Text>
          </View>
          <Text style={styles.cardBody}>{report.alignmentSummary}</Text>
        </View>

        {/* Patterns */}
        {report.ingredientPatterns.length > 0 && (
          <View style={styles.card}>
            <View style={styles.cardHeaderRow}>
              <Text style={styles.cardEmoji}>🔍</Text>
              <Text style={styles.cardTitle}>Patterns Noticed</Text>
            </View>
            <View style={styles.patternList}>
              {report.ingredientPatterns.map((p, i) => (
                <View key={i} style={styles.patternItem}>
                  <View style={styles.patternDot} />
                  <Text style={styles.patternText}>{p}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Recommendations */}
        {report.recommendations.length > 0 && (
          <View style={styles.card}>
            <View style={styles.cardHeaderRow}>
              <Text style={styles.cardEmoji}>💡</Text>
              <Text style={styles.cardTitle}>Recommendations</Text>
            </View>
            <View style={styles.recList}>
              {report.recommendations.map((rec, i) => (
                <View key={i} style={styles.recItem}>
                  <View style={styles.recNumber}>
                    <Text style={styles.recNumberText}>{i + 1}</Text>
                  </View>
                  <Text style={styles.recText}>{rec}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Disclaimer */}
        <Text style={styles.disclaimer}>
          This report is generated by AI based on your meal diary entries. It is not medical advice.
          Always consult a healthcare professional for decisions about your health.
        </Text>

        <View style={{ height: 20 }} />
      </ScrollView>

      {/* Bottom actions */}
      <View style={[styles.bottomActions, { paddingBottom: insets.bottom + 16 }]}>
        <TouchableOpacity style={styles.discardBtn} onPress={handleDiscard} activeOpacity={0.7}>
          <Text style={styles.discardText}>Discard</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.saveBtn} onPress={handleSave} activeOpacity={0.85}>
          <Text style={styles.saveBtnText}>Save to Diary</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.card,
  },
  headerEyebrow: { ...Typography.label, color: Colors.muted },
  headerTitle: { ...Typography.h1, marginTop: 2 },
  headerBadge: {
    backgroundColor: Colors.sageLight,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: Radius.full,
  },
  headerBadgeText: { fontSize: 12, fontWeight: '700', color: Colors.sage },

  scroll: { flex: 1 },
  scrollContent: { padding: Spacing.lg, gap: Spacing.md },

  card: {
    backgroundColor: Colors.card,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
    ...Shadow.sm,
  },
  cardHero: {
    borderLeftWidth: 4,
    borderLeftColor: Colors.sage,
  },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardEmoji: { fontSize: 20 },
  cardTitle: { ...Typography.h3, color: Colors.ink },
  cardBody: { ...Typography.body, color: Colors.muted, lineHeight: 24 },

  patternList: { gap: 10 },
  patternItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  patternDot: {
    width: 8, height: 8, borderRadius: 4,
    backgroundColor: Colors.terracotta, marginTop: 7,
  },
  patternText: { flex: 1, fontSize: 14, color: Colors.ink, lineHeight: 21 },

  recList: { gap: 12 },
  recItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  recNumber: {
    width: 26, height: 26, borderRadius: 13,
    backgroundColor: Colors.sageLight,
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  recNumberText: { fontSize: 13, fontWeight: '700', color: Colors.sage },
  recText: { flex: 1, fontSize: 14, color: Colors.ink, lineHeight: 21 },

  disclaimer: {
    fontSize: 11,
    color: Colors.placeholder,
    textAlign: 'center',
    lineHeight: 17,
    paddingHorizontal: Spacing.md,
  },

  bottomActions: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    gap: Spacing.md,
    backgroundColor: Colors.card,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  discardBtn: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderColor: Colors.border,
    alignItems: 'center',
  },
  discardText: { fontSize: 15, fontWeight: '600', color: Colors.muted },
  saveBtn: {
    flex: 2,
    paddingVertical: 16,
    borderRadius: Radius.lg,
    backgroundColor: Colors.sage,
    alignItems: 'center',
    ...Shadow.sage,
  },
  saveBtnText: { fontSize: 15, fontWeight: '700', color: Colors.card },
});
